name: flutter_heic_to_jpg
description: "A Flutter plugin for converting HEIC images to JPG format on Android and iOS devices. Easily integrate HEIC to JPG conversion into your Flutter apps with a simple API."
repository: https://github.com/TalebRafiepour/flutter_heic_to_jpg.git
version: 1.0.0

topics: 
  - heic
  - heictojpg
  - heicconversion
  - imageconversion


environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_heic_to_jpg
        pluginClass: FlutterHeicToJpgPlugin
      ios:
        pluginClass: FlutterHeicToJpgPlugin

